name: what3words
description: >-
  A Dart library to use the what3words v3 API. This library can either be used in native Dart or Flutter applications
version: 3.1.0
homepage: https://github.com/what3words/w3w-dart-wrapper

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  chopper: ^8.0.1+1
  os_detect: ^2.0.1

dev_dependencies:
  chopper_generator: ^8.0.1
  pedantic: ^1.11.1
  test: ^1.25.7
